#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     EOPD,           sensorAnalog)
#pragma config(Sensor, S3,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftdrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightdrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     encoderMotor,  tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    turning1,             tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    turning2,             tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v2.h" //Include file to "handle" IR seeker


#define DEG90 1000
#define DEG45 (DEG90 / 2)
#define SPEED 25
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	eraseDisplay();

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	// Create struct to hold sensor data
	tHTIRS2 irSeeker;

	// Initialise and configure struct and port
	initSensor(&irSeeker, S3);

	irSeeker.mode = DSP_1200;

	waitForStart(); // Wait for the beginning of autonomous phase.

	readSensor(&irSeeker);

	displayCenteredTextLine(0, "%d", irSeeker.acValues);

	if (irSeeker.acValues[2] < 30)
	{
		displayCenteredTextLine(1, "Position 1");

		motor[leftdrive] = SPEED;

		wait1Msec(DEG45);

		motor[rightdrive] = -SPEED;

		wait1Msec(1200);

		motor[leftdrive] = 0;

		wait1Msec(1200);

		motor[leftdrive] = SPEED;

		wait1Msec(1700);
	}
	else if (irSeeker.acValues[2] < 100)
	{
		displayCenteredTextLine(1, "Position 2");

		motor[leftdrive] = SPEED;
		motor[rightdrive] = -SPEED;

		wait1Msec(1400);

		motor[leftdrive] = 0;

		wait1Msec(300);

		motor[leftdrive] = SPEED;

		wait1Msec(2000);

	}
	else
	{
		displayCenteredTextLine(1, "Position 3");

		motor[rightdrive] = -SPEED;
		motor[leftdrive] = SPEED;

		wait1Msec(1400);

		motor[rightdrive] = 80;
		motor[leftdrive] = -80;

		wait1Msec(10);

		motor[rightdrive] = 0;
		motor[leftdrive] = 0;

		wait1Msec(1500);

		motor[rightdrive] = 0;
		motor[leftdrive] = -25;

		wait1Msec(DEG90);

		motor[rightdrive] = -SPEED;
		motor[leftdrive] = SPEED;

		wait1Msec(1000);

		motor[rightdrive] = 25;
		motor[leftdrive] = 0;

		wait1Msec(DEG90);

		motor[leftdrive] = SPEED;
		motor[rightdrive] = -SPEED;

		wait1Msec(1200);
	}
	motor[rightdrive] = 0;
	motor[leftdrive] = 0;

	while (true)
	{}
}
