#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     mtrSweeper,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mtrKicker,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     mtrLeft1,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     mtrLeft2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     mtrRight1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     mtrRight2,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C3_1,    leftWhisker,          tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    rightWhisker,         tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    Indexer,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    latch,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    towerLatch,           tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-irseeker-v2.h"

#define SPEED 60

/////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////         DECLARING           ////////////////////////////////////////////////////////
////////////////              VARIABLES   ///////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////

int state = 0;   // used to make sure NXT isn't frozen

int delayedstart = 0;   // first thing established -- how long you wait before you start the chosen program

int zone = 0;
int zonevalue1 = 0;
int zonevalue2 = 0;
int zonevalue3 = 0;
int zonevalue4 = 0;
int zonevalue5 = 0;

int first = 0;   // where you begin. Ramp or floor?
int ball = 0;    // what you do next. IR ball and release kickstand, or put ball in rolling goal.
int last = 0;    // what you do last. Go from IR to rolling goal or to defense.

void display()
{

	state = state + 1;   // all of this state stuff is to make sure that the NXT isn't frozen. The number on the screen will
	if(state > 10)       // continually be changing unless the NXT is frozen.
	{
		state = 0;
	}

	eraseDisplay();

	nxtDisplayTextLine(0, "4507           %d", state); // Reestablishing what the NXT would normally display because we erased the display
	nxtDisplayTextLine(2, "                ");   // Program name -- fill in here
	nxtDisplayTextLine(3, "Ext Batt:%4.1f V", externalBatteryAvg / (float) 1000);  // Display external battery voltage
	nxtDisplayTextLine(4, "NXT Batt:%4.1f V", nAvgBatteryLevel / (float) 1000);   // Display NXT Battery Voltage
}

int button = 0;   // integer that establishes the NXT buttons

int buttons()
{
	button = 0;
	switch(nNxtButtonPressed)
	{
	case kLeftButton:
		button = 1;
		playSound(soundBlip);

		break;

	case kRightButton:
		button = 2;
		playSound(soundBlip);

		break;

	case kEnterButton:
		button = 3;
		playSound(soundBlip);

		break;

	case kExitButton:
		button = 4;
		playSound(soundBlip);

		break;
	}
	return button;
}

int hold = 1;   // resets between "sections"
int pos = 1;    // screen position

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	disableDiagnosticsDisplay();

	delayedstart = 0;
	wait1Msec(500);

	while(hold == 1)
	{
		nxtDisplayTextLine(0, "4507            ");
		nxtDisplayTextLine(1, "                ");
		nxtDisplayTextLine(2, "START DELAY TIME");
		nxtDisplayTextLine(3, "                ");
		nxtDisplayTextLine(4, "      %d",delayedstart);
		nxtDisplayTextLine(5, "                ");
		nxtDisplayTextLine(6, "                ");
		nxtDisplayTextLine(7, "      IN SECONDS");

		buttons();

		if(button == 1)
		{
			delayedstart --;          // subtract one at a time from the start time when you press the left button
			if (delayedstart < 0)
			{
				delayedstart = 0;
			}
			wait1Msec(500);
		}
		if(button == 2)
		{
			delayedstart ++;         // add one at a time to the start time when you press the right button
			if (delayedstart > 30)
			{
				delayedstart = 30;
			}
			wait1Msec(500);
		}
		if(button == 3)
		{
			hold = 0;
			wait1Msec(500);
		}
	}


	hold = 1;
	wait1Msec(500);

	while (hold == 1)
	{
		if (pos == 1)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, "                ");
			nxtDisplayTextLine(2, "         ____   ");
			nxtDisplayTextLine(3, "      _<     I  ");
			nxtDisplayTextLine(4, "   _<        I  ");
			nxtDisplayTextLine(5, " <___________I  ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, " Start from Ramp");

			buttons();

			if (button == 1)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 3)
			{
				first = -1;
				pos = 1;
				hold = 0;
			}
		}

		if (pos == 2)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, " FFFFFFFF       ");
			nxtDisplayTextLine(2, " F              ");
			nxtDisplayTextLine(3, " FFFF           ");
			nxtDisplayTextLine(4, " F              ");
			nxtDisplayTextLine(5, " F              ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, "Start on Floor  ");

			buttons();

			if (button == 1)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 3)
			{
				first = 1;
				pos = 1;
				hold = 0;
			}
		}
	}

	hold = 1;
	wait1Msec(500);

	while (hold == 1)
	{
		if (pos == 1)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, " III RRRRRR     ");
			nxtDisplayTextLine(2, "  I  R    R     ");
			nxtDisplayTextLine(3, "  I  RRRRR      ");
			nxtDisplayTextLine(4, "  I  R  R       ");
			nxtDisplayTextLine(5, " III R   R      ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, "Go for IR ball  ");

			buttons();

			if (button == 1)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 3)
			{
				ball = -1;
				pos = 1;
				hold = 0;
			}
		}
		if (pos == 2)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, " RRRR  GGGGG    ");
			nxtDisplayTextLine(2, " R  R  G        ");
			nxtDisplayTextLine(3, " RRR   G GGG    ");
			nxtDisplayTextLine(4, " R  R  G   G    ");
			nxtDisplayTextLine(5, " R   R GGGGG    ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, "Rollinggoal,ball");

			wait1Msec(500);

			buttons();

			if (button == 1)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 3)
			{
				ball = 1;
				pos = 1;
				hold = 0;
			}
		}
	}

	hold = 1;
	wait1Msec(500);

	if (ball != 1)

	while(hold == 1)
	{
		if (pos == 1)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, " RRRR  GGGGG    ");
			nxtDisplayTextLine(2, " R  R  G        ");
			nxtDisplayTextLine(3, " RRR   G GGG    ");
			nxtDisplayTextLine(4, " R  R  G   G    ");
			nxtDisplayTextLine(5, " R   R GGGGG    ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, "RG 90 cm ball 2 ");

			buttons ();

			if (button == 1)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 2;
				wait1Msec(500);
			}
			if (button == 3)
			{
				last = -1;
				pos = 1;
				hold = 0;
			}
		}
		if (pos == 2)
		{
			nxtDisplayTextLine(0, "4507            ");
			nxtDisplayTextLine(1, " DDDDDDD        ");
			nxtDisplayTextLine(2, " D      D       ");
			nxtDisplayTextLine(3, " D      D       ");
			nxtDisplayTextLine(4, " D      D       ");
			nxtDisplayTextLine(5, " DDDDDDD        ");
			nxtDisplayTextLine(6, "                ");
			nxtDisplayTextLine(7, "    Defense     ");

			wait1Msec(500);

			buttons();

			if (button == 1)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 2)
			{
				pos = 1;
				wait1Msec(500);
			}
			if (button == 3)
			{
				last = 1;
				pos = 1;
				hold = 0;
			}
		}
	}


	nxtDisplayTextLine(0, "                ");
	nxtDisplayTextLine(1, "                ");
	nxtDisplayTextLine(2, "                ");
	nxtDisplayTextLine(3, "                ");
	nxtDisplayTextLine(4, "                ");
	nxtDisplayTextLine(5, "                ");
	nxtDisplayTextLine(6, "                ");
	nxtDisplayTextLine(7, "                ");






	nxtDisplayTextLine(0, "4507            ");
	nxtDisplayTextLine(1, "================");
	nxtDisplayTextLine(3, "Delay         %d",delayedstart);
	if(first == -1)
	{
		nxtDisplayTextLine(4, "            Ramp");
	}
	if(first == 1)
	{
		nxtDisplayTextLine(4, "           Floor");
	}
	if(ball == -1)
	{
		nxtDisplayTextLine(5, "              IR");
	}
	if(ball == 1)
	{
		nxtDisplayTextLine(5, "    Rolling Goal");
	}

	if(last == -1)
	{
		nxtDisplayTextLine(6, "    Rolling Goal");
	}
	if(last == 1)
	{
		nxtDisplayTextLine(6, "         Defense");
	}

	return;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//   areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	if (first == -1)
	{
		if (ball == 1)
		{
			motor[mtrRight1] = -SPEED;
			motor[mtrRight2] = -SPEED;   //drive off ramp
			motor[mtrLeft1] = SPEED;
			motor[mtrLeft2] = SPEED;

			wait1Msec(1000);

			motor[mtrRight1] = -20;
			motor[mtrRight2] = -20;   //slow down, but still driving forward
			motor[mtrLeft1] = 20;
			motor[mtrLeft2] = 20;

			wait1Msec(2010);

			motor[mtrRight1] = 0;
			motor[mtrRight2] = 0;   //stop at 60 cm tube
			motor[mtrLeft1] = 0;
			motor[mtrLeft2] = 0;

			wait1Msec(2010);

			servo[towerLatch] = 0;  //tower goes up

			wait1Msec(1000);

			motor[mtrKicker] = 75;  //kick ball into tube

			wait1Msec(4000);

			motor[mtrKicker] = 0;    //turn kicker off
		}
		if (last == -1)
		{
			motor[mtrRight1] = SPEED;
			motor[mtrRight2] = SPEED;
			motor[mtrLeft1] = -SPEED;   //drive backward
			motor[mtrLeft2] = -SPEED;

			wait1Msec(500);

			motor[mtrRight1] = SPEED;  //turn 1, away to drop off the 60 cm tube
			motor[mtrRight2] = SPEED;
			motor[mtrLeft1] = SPEED;
			motor[mtrLeft2] = SPEED;

			wait1Msec(600);

			motor[mtrRight1] = 0;
			motor[mtrRight2] = 0;
			motor[mtrLeft1] = 0;
			motor[mtrLeft2] = 0;

			motor[mtrRight1] = -SPEED;
			motor[mtrRight2] = -SPEED;  //drive forward to drop off 60 cm
			motor[mtrLeft1] = SPEED;
			motor[mtrLeft2] = SPEED;

			wait1Msec(600);

			servo[latch] = 215; //latch releases 60 cm tube

			motor[mtrRight1] = 0;
			motor[mtrRight2] = 0;
			motor[mtrLeft1] = 0;
			motor[mtrLeft2] = 0;

			motor[mtrRight1] = SPEED;
			motor[mtrRight2] = SPEED;
			motor[mtrLeft1] = -SPEED;   //drive backward
			motor[mtrLeft2] = -SPEED;

			wait1Msec(600);

			motor[mtrRight1] = -SPEED;
			motor[mtrRight2] = -SPEED;
			motor[mtrLeft1] = -SPEED;   //turn 2, go for 90 cm tube
			motor[mtrLeft2] = -SPEED;

			wait1Msec(600);

			motor[mtrRight1] = 0;
			motor[mtrRight2] = 0;
			motor[mtrLeft1] = 0;
			motor[mtrLeft2] = 0;

			motor[mtrRight1] = -SPEED;     //drive forward to get 90 cm tube
			motor[mtrRight2] = -SPEED;
			motor[mtrLeft1] = SPEED;
			motor[mtrLeft2] = SPEED;

			wait1Msec(1100);

			motor[mtrRight1] = 0;
			motor[mtrRight2] = 0;
			motor[mtrLeft1] = 0;
			motor[mtrLeft2] = 0;

			wait1Msec(1000);

			servo[latch] = 185; //latch 90 cm

			wait1Msec(1000);

			servo[Indexer] = 215;

			servo[Indexer] = 255;

			motor[mtrKicker] = 75;  //kick ball into 90 cm

			wait1Msec(4000);

			motor[mtrKicker] = 0;
		}
	}

	if (first == 1)
	{

	}
}
