#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S2_C1_1,     mtrRight1,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mtrLeft1,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     mtrSweeper,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     mtrRight2,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     mtrLeft2,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     mtrKicker,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C3_1,    leftWhisker,          tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    rightWhisker,         tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    Indexer,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    latch,                tServoStandard)
#pragma config(Servo,  srvo_S2_C3_6,    towerLatch,           tServoStandard)
#pragma config(Servo,  srvo_S4_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#define SPEED 50

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	servo[latch] = 235;

	wait1Msec(500);

	motor[mtrRight1] = -SPEED;
	motor[mtrRight2] = -SPEED;   //drive off ramp
	motor[mtrLeft1] = SPEED;
	motor[mtrLeft2] = SPEED;

	wait1Msec(1500);

	motor[mtrRight1] = -20;
	motor[mtrRight2] = -20;   //slow down, but still driving forward
	motor[mtrLeft1] = 20;
	motor[mtrLeft2] = 20;

	wait1Msec(2100);

	motor[mtrRight1] = 0;
	motor[mtrRight2] = 0;
	motor[mtrLeft1] = 0;
	motor[mtrLeft2] = 0;

	wait1Msec(2010);

	servo[towerLatch] = 180;

	wait1Msec(1000);

	motor[mtrKicker] = 75;

	wait1Msec(4000);

	motor[mtrKicker] = 0;

	servo[latch] = 200;

	while (true)
	{}
}
