#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     Chain2,         sensorNone)
#pragma config(Sensor, S3,     kickTouch,      sensorTouch)
#pragma config(Sensor, S4,     Chain4,         sensorNone)
#pragma config(Motor,  mtr_S2_C1_1,     rightTop,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     leftTop,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rightBot,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     leftBot,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     kicker,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C3_1,    leftWhisker,          tServoStandard)
#pragma config(Servo,  srvo_S2_C3_2,    rightWhisker,         tServoStandard)
#pragma config(Servo,  srvo_S2_C3_3,    indexer,              tServoStandard)
#pragma config(Servo,  srvo_S2_C3_4,    goalLatch,            tServoStandard)
#pragma config(Servo,  srvo_S2_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C3_6,    towerLatch,           tServoStandard)
#pragma config(Servo,  srvo_S4_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "hitechnic-eopd.h"
//#include "hitechnic-irseeker-v2.h"
#include "joystickDriver.c"
#include "lego-touch.h"

bool indexVariable = false;
bool indexerStop = false;
bool indexToggle = false;

int indexTime;

void index()
{
	if(indexerStop == false)
	{
		if((TSreadState(kickTouch) == 1) && (indexVariable == false))
		{
			indexVariable = true;
		}

		if((TSreadState(kickTouch) == 0) && (indexVariable == true))
		{
			servo[indexer] = 215;
			indexVariable = false;
			indexTime = time100[T3];
		}
		else if(time100[T3] >= indexTime + 5)
		{
			servo[indexer] = 255;
		}
	}
	else
	{
		servo[indexer] = 255;
	}

	if(((joy1Btn(8) == 1) || (joy2Btn(8) == 1)) && (indexToggle == false))
	{
		indexToggle = true;
		if(indexerStop == true)
		{
			indexerStop = false;
		}
		else
		{
			indexerStop = true;
		}
	}

	if(((joy1Btn(8) == 0) && (joy2Btn(8) == 0)) && (indexToggle == true))
	{
		indexToggle = false;
	}

	return;
}

task main ()
{
	/*tHTEOPD eopd1Sensor;
	tHTEOPD eopd2Sensor;
	tHTIRS2 irSeeker;
	initSensor(&eopd1Sensor, msensor_S4_1);					// declare the sensor multiplexor setup
	initSensor(&eopd2Sensor, msensor_S4_2);
	initSensor(&irSeeker, msensor_S4_3);
	eopd1Sensor.shortRange = true;
	configSensor(&eopd1Sensor);*/

	int threshold = 10;             /* Int 'threshold' will allow us to ignore low       */
	/* readings that keep our robot in perpetual motion. */
	//int ballDist;
	int bigLow = 65;
	int bigHigh = 75;
	int smallLow = 35;
	int smallHigh = 49;
	//int kicked;
	int latchGo;
	int latchPressed;

	bool sweeperForward = false;
	bool sweeperBackwards = false;
	bool forwardPressed = false;
	bool reversePressed = false;
	bool kickerRun = false;
	bool kickerPressed = false;
	bool initIndex = false;
	bool TSKickPressed = false;
	bool TSKickRun = false;
	bool firstTime = false;
	bool touchSensor = false;
	bool doorPressed = false;
	bool doorOpen = false;

	waitForStart();

	while(true)                            // Infinite loop:
	{
		getJoystickSettings(joystick);
		/*readSensor(&eopd1Sensor);
		readSensor(&eopd2Sensor);
		readSensor(&irSeeker);*/

		if(abs(joystick.joy1_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
			motor[rightTop] = joystick.joy1_y2*128/100;         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
			motor[rightBot] = joystick.joy1_y2*128/100;
		}
		else                                    // Else if the readings are within the threshold:
		{
			motor[rightTop] = 0;                        // Motor B is stopped with a power level of 0.
			motor[rightBot] = 0;
		}


		if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
			motor[leftTop] = joystick.joy1_y1*-128/100;         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
			motor[leftBot] = joystick.joy1_y1*-128/100;
		}
		else                                    // Else if the readings are within the threshold:
		{
			motor[leftTop] = 0;                        // Motor C is stopped with a power level of 0.
			motor[leftBot] = 0;
		}

		if(((joy1Btn(3) == 1) || (joy2Btn(3) == 1)) && (forwardPressed == false))		//if the forward button is pressed and it has not been pressed before
		{
			forwardPressed = true;									// Say the button has been pressed
			if(sweeperForward == false)									// if the sweeper is not moving forwards
			{
				motor[sweeper] = 87;									// make it move
				sweeperForward = true;									// remember that it is moving
			}
			else																			// if the sweeper is moving
			{
				motor[sweeper] = 0;											// make it stop
				sweeperForward = false;								// remember that it is stopped
			}
		}

		if(((joy1Btn(3) == 0) && (joy2Btn(3) == 0)) && (forwardPressed == true))			// if the forward button is not pressed and the button has been pressed
		{
			forwardPressed = false;														// remember that the button is not pressed
		}

		if(((joy1Btn(1) == 1) || (joy2Btn(1) == 1)) && (reversePressed == false))			// if the reverse button is pressed and it has not been pressed before
		{
			reversePressed = true;															// remember that the reverse button has been pressed
			if(sweeperBackwards == false)											// if the sweeper is not moving backwards
			{
				motor[sweeper] = -87;														// make it move backwards
				sweeperBackwards = true;												// remember that the sweeper is moving backwards
			}
			else																						// if the sweeper is moving backwards
			{
				motor[sweeper] = 0;														// make it stop moving
				sweeperBackwards = false;											// remember that the sweeper is not moving backwards
			}
		}

		if(((joy1Btn(1) == 0) && (joy2Btn(1) == 0)) && (reversePressed == true))			// if the backwards button is not pressed and it hsa been pressed
		{
			reversePressed = false;															// remember the button is not pressed
		}

		if((joy1Btn(7) == 1) || (joy2Btn(7) == 1))										// if button is pressed
		{
			servo[leftWhisker] = 0;
			servo[rightWhisker] = 150;						// both whiskers move 70 degrees. Try values!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		}																				// Try Values!!!!!!!!!!!!!!!!!!
		else																// if button is not pressed
		{
			servo[leftWhisker] = 160;						// neither whiskers activate
			servo[rightWhisker] = 0;
		}

		/*if(TSreadState(msensor_S4_4))
		{
		displayCenteredBigTextLine(3, "ACTIVE");
		}
		else
		{
		displayCenteredBigTextLine(3, "INACTIVE");
		}

		if(joy1Btn(4) == 1)									// if button is pressed
		{
		servo[latch] = 90;										// grabber will move to resting position
		}
		else
		{
		if((TSreadState(msensor_S4_4)) || (joy1Btn(8) == 1))				// if touch sensor or button 8 is pressed
		{
		servo[latch] = 180;					// latch will activate
		}
		}

		ballDist = (1023 - eopd1Sensor.raw);									// display reading on the NXT - big or small and the numerical value
		displayBigTextLine(1, "%d", ballDist);*/

		if(((joy1Btn(6) == 1) || (joy2Btn(6) == 1)) && (kickerPressed == false))		//if the button is pressed and it has not been pressed before
		{
			kickerPressed = true;									// Say the button has been pressed
			if(kickerRun == false)									// if the sweeper is not moving forwards
			{
				motor[kicker] = 85;									// make it move
				kickerRun = true;									// remember that it is moving
			}
			else																			// if the sweeper is moving
			{
				motor[kicker] = 0;											// make it stop
				kickerRun = false;
				firstTime = false;																					// remember that it is stopped
			}
		}
		else if((joy1Btn(6) == 0) && (joy2Btn(6) == 0))
		{
			kickerPressed = false;
		}

		if(((joy1Btn(4) == 1) || (joy2Btn(4) == 1)) && (doorPressed == false))		//if the button is pressed and it has not been pressed before
		{
			doorPressed = true;									// Say the button has been pressed
			if(doorOpen == false)									// if the sweeper is not moving forwards
			{
				servo[servo5] = 200;									// make it move
				doorOpen = true;									// remember that it is moving
			}
			else																			// if the sweeper is moving
			{
				servo[servo5] = 200;											// make it stop
				doorOpen = false;																				// remember that it is stopped
			}
		}
		else if((joy1Btn(4) == 0) && (joy2Btn(4) == 0))
		{
			doorPressed = false;
		}

		if(((joy1Btn(5) == 1) || (joy2Btn(5) == 1)) && (latchPressed == false))		//if the forward button is pressed and it has not been pressed before
		{
			latchPressed = true;									// Say the button has been pressed
			if(latchGo == false)									// if the sweeper is not moving forwards
			{
				servo[goalLatch] = 70;									// make it move
				servo[servo5] = 0;
				latchGo = true;
				playSound(soundFastUpwardTones);		// remember that it is moving
			}
			else																			// if the sweeper is moving
			{
				servo[goalLatch] = 110;								//This is parallel to the ground
				servo[servo5] = 180;
				latchGo = false;
			}
		}

		if(((joy1Btn(5) == 0) && (joy2Btn(5) == 0)) && (latchPressed == true))			// if the forward button is not pressed and the button has been pressed
		{
			latchPressed = false;														// remember that the button is not pressed
		}

		index();

		//if((joy1Btn(2) == 1) || (joy2Btn(2) == 1))
		//{
		//	servo[servo5] = 180;
		//}
		//else
		//{
		//	servo[servo5] = 0;
		//}

	}
}
